version: '3' 
services:

  db:
    image: postgres:alpine
    container_name: db-container
    ports: 
      - "5432:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGTZ: Asia/Tokyo
  
  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
       - redis-data:/data
    restart: always
    tty: true
    environment:
      TZ: Asia/Tokyo

  web: 
    container_name: web-container
    build: . 
    command: >
      bash -c "
      python3 manage.py runserver 0.0.0.0:8000 
      "
    volumes:
      - .:/code
    ports:
      - "80:8000"
    restart: always
    depends_on:
      - db
      - redis

volumes: 
  db-data:
    driver: local

  redis-data:
    driver: local